# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170910_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='qualifications',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='requirements',
            new_name='responsibilities',
        ),
        migrations.AddField(
            model_name='post',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='transcript',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='why_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='openings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
