# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160807_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='openings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='wage',
            field=models.IntegerField(null=True),
        ),
    ]
