# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160807_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
