# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
