# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='supplied_by_jobin',
            field=models.BooleanField(default=True),
        ),
    ]
