# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20160809_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='post_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
