# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20160901_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
