# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20160928_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
