# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_cover_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='open', max_length=50, null=True),
        ),
    ]
