# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20161020_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_startup_post',
            field=models.BooleanField(default=False),
        ),
    ]
