# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_is_startup_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='new_apps',
            field=models.BooleanField(default=False),
        ),
    ]
