# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20161103_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='post',
            name='wage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
