# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20161124_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='post_title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='student_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
