# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20170316_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wage_interval',
            field=models.CharField(default='month', max_length=20),
            preserve_default=False,
        ),
    ]
