# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
