# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='city', max_length=200),
            preserve_default=False,
        ),
    ]
