# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_auto_20160807_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('schools', models.CharField(default='ALL', max_length=200, null=True)),
                ('programs', models.CharField(default='ALL', max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=50, null=True)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
        ),
    ]
