# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
