# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20161107_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinterest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
