# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventinterest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinterest',
            name='date',
            field=models.DateField(default=datetime.date(2016, 12, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
