# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20161208_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventInterest',
            new_name='SavedEvent',
        ),
    ]
