# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20170428_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date(2017, 4, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 43, 53, 340654)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='programs',
            field=models.CharField(default='ALL', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='schools',
            field=models.CharField(default='ALL', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 4, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 44, 10, 803740)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='zipcode',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedevent',
            name='event_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
