# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20170428_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedevent',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='savedevent',
            name='end_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedevent',
            name='start_date',
            field=models.DateField(default='2002-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedevent',
            name='start_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
