# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20170807_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
