# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobinterritory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinschool',
            name='email',
            field=models.CharField(default='ubishops.ca', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinterritory',
            name='country',
            field=models.CharField(default='Canada', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
