# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobinrequestedemail_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobinRequestedSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
