# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_linkedin'),
        ('company', '0004_company_country'),
        ('home', '0003_auto_20160916_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=250)),
                ('opened', models.BooleanField(default=False)),
                ('internal', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
