# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160916_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='opened',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.AlterField(
            model_name='notification',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
