# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160928_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobinBlockedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobinRequestedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=50)),
            ],
        ),
    ]
