# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobininvaliduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2002-02-02 00:00:00'),
            preserve_default=False,
        ),
    ]
