# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170316_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobininvaliduser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2002-02-02 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='message',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
