# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
