# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
