# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_startup',
            field=models.BooleanField(default=False),
        ),
    ]
