# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_is_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
