# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20170426_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(default='industry', max_length=100),
            preserve_default=False,
        ),
    ]
