# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('suggestion', models.TextField()),
                ('importance', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('resolution_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
            ],
        ),
    ]
