# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
