# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20160901_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
