# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
