# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180109_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_requested',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
