# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='work_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
