# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_work_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
