# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20161124_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='address', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='city', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(default='country', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='email', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='major', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(default='program', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(default='schoo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(default='state', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='zipcode',
            field=models.CharField(default='zip', max_length=20),
            preserve_default=False,
        ),
    ]
