# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20170426_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateField(default='2017-02-02'),
            preserve_default=False,
        ),
    ]
