# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_student_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
