# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
