# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
