# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_experience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
