# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20161014_1442'),
        ('resume', '0007_auto_20161014_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
        ),
        migrations.RemoveField(
            model_name='award',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='language',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='school',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.AddField(
            model_name='award',
            name='student',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='student',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='student',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='student',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='student.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='student',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilllink',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Skill'),
        ),
        migrations.AddField(
            model_name='schoollink',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.School'),
        ),
        migrations.AddField(
            model_name='languagelink',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Language'),
        ),
        migrations.AddField(
            model_name='languagelink',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='experiencelink',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Experience'),
        ),
        migrations.AddField(
            model_name='experiencelink',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='awardlink',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Award'),
        ),
        migrations.AddField(
            model_name='awardlink',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
