# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20161025_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencelink',
            name='start',
            field=models.DateField(default=datetime.datetime(2016, 10, 25, 10, 41, 0, 984477, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
