# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20161025_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
