# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20161025_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='rname',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='rname',
            field=models.CharField(default='rname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='rname',
            field=models.CharField(default='rname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='rname',
            field=models.CharField(default='rname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='rname',
            field=models.CharField(default='rname', max_length=100),
            preserve_default=False,
        ),
    ]
