# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20161031_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
