# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20161208_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='gpa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
