# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20170404_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='awardlink',
            unique_together=set([('resume', 'award')]),
        ),
        migrations.AlterUniqueTogether(
            name='experiencelink',
            unique_together=set([('resume', 'experience')]),
        ),
        migrations.AlterUniqueTogether(
            name='languagelink',
            unique_together=set([('resume', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='schoollink',
            unique_together=set([('resume', 'school')]),
        ),
        migrations.AlterUniqueTogether(
            name='skilllink',
            unique_together=set([('resume', 'skill')]),
        ),
    ]
